// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjL1wsFzfzcRVx7l9C1JNcoIbMStOvTIQ',
    appId: '1:229895546002:web:13c45a2c46671069b4f24b',
    messagingSenderId: '229895546002',
    projectId: 'remotegatecontroller-82180',
    authDomain: 'remotegatecontroller-82180.firebaseapp.com',
    storageBucket: 'remotegatecontroller-82180.firebasestorage.app',
    measurementId: 'G-ZE35X33GPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLhGJA6AnOiJJSZXPuhHfnVAiQnP8dgM',
    appId: '1:229895546002:android:2aa833c5c4c9485fb4f24b',
    messagingSenderId: '229895546002',
    projectId: 'remotegatecontroller-82180',
    storageBucket: 'remotegatecontroller-82180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwMT-mcbR2Vsk-6l6W5XZ8jIhe5hmVkZk',
    appId: '1:229895546002:ios:84e5d5823e827195b4f24b',
    messagingSenderId: '229895546002',
    projectId: 'remotegatecontroller-82180',
    storageBucket: 'remotegatecontroller-82180.firebasestorage.app',
    iosBundleId: 'com.mobile.remoteGateControlMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwMT-mcbR2Vsk-6l6W5XZ8jIhe5hmVkZk',
    appId: '1:229895546002:ios:84e5d5823e827195b4f24b',
    messagingSenderId: '229895546002',
    projectId: 'remotegatecontroller-82180',
    storageBucket: 'remotegatecontroller-82180.firebasestorage.app',
    iosBundleId: 'com.mobile.remoteGateControlMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjL1wsFzfzcRVx7l9C1JNcoIbMStOvTIQ',
    appId: '1:229895546002:web:3c6d368ee57b7eafb4f24b',
    messagingSenderId: '229895546002',
    projectId: 'remotegatecontroller-82180',
    authDomain: 'remotegatecontroller-82180.firebaseapp.com',
    storageBucket: 'remotegatecontroller-82180.firebasestorage.app',
    measurementId: 'G-H4MLD071GZ',
  );
}
